server:
  port: ${PORT:8082}
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: db-tcc-123
        platform: mysql
        url: jdbc:mysql://172.17.0.2/starwars
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
logging:
  level:
    ROOT: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    br.com.ricardoludwig.starwars: DEBUG
        
---
spring:
    profiles: heroku
    datasource:
        driver-class-name: org.postgresql.Driver
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
        platform: postgresql
        url: ${JDBC_DATABASE_URL}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: true
